# Generated by Django 3.0.2 on 2020-05-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_ceil_floor_params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_col', models.IntegerField()),
                ('col_index', models.IntegerField()),
                ('ceil_mode', models.IntegerField()),
            ],
        ),
    ]
