# Generated by Django 2.2.6 on 2019-10-21 18:09

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists within the DigitalCognition user database , kindly choose another username.'}, help_text='<div style="color:grey;"> Username is a Required Field. Your UserName for <strong><b>DigitalCognition</b></strong> can have max - 150 characters. You may use Letters, digits and @/./+/-/_ only.</div>', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
